# Generated by Django 2.1.3 on 2018-11-18 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('livebroadcast', '0002_auto_20181110_0714'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=255)),
                ('visitor', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('date_time', models.DateTimeField()),
                ('livebroadcast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='livebroadcast.Livebroadcast')),
            ],
        ),
        migrations.AlterField(
            model_name='trip',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
    ]
