# Generated by Django 2.1.3 on 2018-11-19 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livebroadcast', '0003_auto_20181118_2336'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='visitor',
            new_name='user',
        ),
    ]
