# Generated by Django 2.1.3 on 2018-11-28 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livebroadcast', '0004_auto_20181119_2245'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['date_time'], 'permissions': (('can_comment', 'Can comments'),)},
        ),
    ]
